import type { Metadata } from "next";
import "./globals.css";
import SuppressHydrationWarning from "@/components/suppress-hydration-warning";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SuppressHydrationWarning>{children}</SuppressHydrationWarning>
      </body>
    </html>
  );
}
